import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Landing UAPA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/landing.ico" />
      </Head>



      <article className={styles.fondoBlanco}>
        <section className={styles.fondoImagen}>
          <Navbar></Navbar>
          <h1 className={styles.letrasIniciales}>
            The best products start with Figma
          </h1>
          <h4 className={styles.letrasMedio}>Most calendars are designed for teams. Slate is designed 
for freelancers</h4>
          <button className={styles.botonFancy}>
            Try For Free
          </button>
       <div className={styles.flex1}>
       <div className={styles.trianguloIzq}></div>
          <div className={styles.trianguloDer}></div>
       </div>
        </section>

      </article>





      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  )
}

export default Home
