import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'
import Infodiv from '../components/divFeat'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
    <main className={styles.main}>
      <Head>
        <title>Landing UAPA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/landing.ico" />
      </Head>

      <article className={styles.fondoBlanco}>
        <section className={styles.fondoImagen}>
          <Navbar></Navbar>
          <h1 className={styles.letrasIniciales} id="Home">
            The best products start with Figma
          </h1>
          <h4 className={styles.letrasMedio}>Most calendars are designed for teams. Slate is designed
            for freelancers</h4>
          <button className={styles.botonFancy}>
            Try For Free
          </button>
          <div className={styles.flex1}>
            <div className={styles.trianguloIzq}></div>
            <div className={styles.trianguloDer}></div>
          </div>
        </section>
       
        <section className={styles.features}>
      <h2 className={styles.tituloF} id="Product">Features</h2>
      <h4 className={styles.subtituloF}>Most calendars are designed for teams. 
Slate is designed for freelancers</h4>
      <div className={styles.flex2}>
      <Infodiv {...["/circ_cuad.png", "OpenType features Variable fonts", "Slate helps you see how many more days you need to work to reach your financial goal."]} />
      <Infodiv {...["/lapiz_trazo.png", "Design with real data", "Slate helps you see how many more days you need to work to reach your financial goal."]} />
      <Infodiv {...["/lapiz.png", "Fastest way to take action", "Slate helps you see how many more days you need to work to reach your financial goal."]} />         

      </div>
      <div >
      <img src={"/screen.png"} width={1000} height={600} className={styles.imgGrande}></img>
      <img src={"/play.png"} width={150} height={150} className={styles.playB}/>
      <img src={"/trianguloP.png"} width={38} height={38} className={styles.playTB}/>
     
      </div>
      </section>
     
      </article>  

     






    </main>
    <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer></div>
  )
}

export default Home
